### PR TITLE
Traversal Trees

### LINKED ISSUE #115: faster production matching while earley parsing
## What

while working on nullable rules (#113), profiling showed a potential for performance improvement.

`ProductionMatching` owns matching productions with terms. currently, it is implemented:

```rust
pub(crate) struct ProductionMatching<'gram> {
    pub prod_id: ProductionId,
    pub lhs: &'gram crate::Term,
    /// "right hand side" [`TermMatching`]s which are partitioned by the matched and unmatched.
    /// For example: [Matched, Matched, Matched, Unmatched, Unmatched]
    rhs: Vec<TermMatching<'gram>>,
    /// The progress cursor used to separate [`TermMatching`]s in the "right hand side"
    matched_count: usize,
}
```

The `rhs` vector requires a fair amount of dynamic memory alloc and free while parsing ([current location](https://github.com/shnewto/bnf/blob/f3ca02101c71636be2d0e7e1605578e63767082c/src/earley/grammar.rs#L115) where vector is cloned).

There may be a better way to model matching terms.

## Brainstorm

If you pick this up, do not take this brainstorm as "the only way". This is just one of many possibilities.

### Trie

instead of cloning the matching vector, matching could be modeled as a Trie/Stemming tree, with each node a `Term`

eg. `<word> ::= 'B' 'A' 'D' | 'B' 'A' 'T'`

```mermaid
graph TD
    S[start matching prod] --> B
    B --> A
    A --> T
    A --> D
```

Then each `ProductionMatching` references a single node in this matching tree.

## Results

To check results, the `criterion` benchmarking can be used:

> cargo criterion

Tracing can be used to investigate:

> CARGO_PROFILE_BENCH_DEBUG=true cargo flamegraph --bench bnf -- --bench

### LINKED ISSUE #117: Nullable productions (Still, Still) Fail to Match
Related to #108 and #112 – failures reproduce on `0.4.0 ≤ bnf ≤ 0.4.3` so _not_ a regression from #113 .

Hit more cases where nullable productions aren't handled properly.

This example looks contrived but was adapted from a larger grammar I'm writing.

As usual, thanks for all your work @CrockAgile !

Sadly, this correctness issue continues to be a total blocker preventing me from adopting `bnf`

Hoping my battle-testing hasn't been in vain and there's an easy fix around the corner 🙏🏻

```rs
use bnf::Grammar;

#[test]
fn test() {
    let fails: &str = "
    <disjunction> ::= <predicate> | <disjunction> <or> <predicate>
    <predicate> ::= <char_null_one> | <special-string> '.'

    <char_null_one> ::= <char_null_two>
    <char_null_two> ::= <char_null_three>
    <char_null_three> ::= <char>

    <or> ::= <ws> 'or' <ws>
    <ws> ::= <whitespace> | ' ' <ws>
    <whitespace> ::= ' '

    <special-string> ::= <special-char> | <special-char> <special-string>
    <special-char> ::= <char> | <whitespace>
    <char> ::= 'a'
    ";

    let input = "a or a";

    let passes_1 = fails.replace(
        // skip nullable production <char_null_two>
        "<char_null_one> ::= <char_null_two>",
        "<char_null_one> ::= <char_null_three>",
    );
    assert!(passes_1.parse::<Grammar>().unwrap().parse_input(input).next().is_some());

    let passes_2 = fails.replace(
        // replace <whitespace> with its terminal ' '
        "<ws> ::= <whitespace> | ' ' <ws>",
        "<ws> ::= ' ' | ' ' <ws>",
    );
    assert!(passes_2.parse::<Grammar>().unwrap().parse_input(input).next().is_some());

    let passes_3 = fails.replace(
        // again, replace <whitespace> with its terminal ' '
        "<special-char> ::= <char> | <whitespace>",
        "<special-char> ::= <char> | ' '",
    );
    assert!(passes_3.parse::<Grammar>().unwrap().parse_input(input).next().is_some());

    assert!(
        fails.parse::<Grammar>().unwrap().parse_input(input).next().is_some(),
        "all grammars except last one parsed: {input}"
    );
}
```

### LINKED ISSUE #118: Right-recursive productions Fail to Match
Looks related to nullable productions: #108 #112 #117

This grammar fails to match when we change a production from **left-recursive** to **right-recursive**.

The left-recursive grammar failed on `0.4.0 ≤ bnf ≤ 0.4.1` – the right-recursive still fails on `0.4.0 ≤ bnf ≤ 0.4.3`

So this issue must have been partially addressed by @CrockAgile in #109 (`0.4.2`)

Happy to help battle-testing any proposed fixes ⚔️

```rs
use bnf::Grammar;

#[test]
fn test() {
    let input = "aa a";

    let left_recursive: &str = "
    <conjunction> ::= <conjunction> <ws> <predicate> | <predicate>
    <predicate> ::= <string_null_one> | <special-string> '.'

    <string_null_one> ::= <string_null_two>
    <string_null_two> ::= <string_null_three>
    <string_null_three> ::= <string>

    <string> ::= <char_null> | <string> <char_null>
    <special-string> ::= <special-char> | <special-string> <special-char>

    <char_null> ::= <char>
    <char> ::= 'a'

    <special-char> ::= <char_null> | <whitespace>
    <whitespace> ::= ' '

    <ws> ::= ' ' | ' ' <ws>
    ";
    assert!(left_recursive.parse::<Grammar>().unwrap().parse_input(input).next().is_some());

    let right_recursive = left_recursive.replace(
        // rewrite production from left- to right- recursive
        "<string> ::= <char_null> | <string> <char_null>",
        "<string> ::= <char_null> | <char_null> <string>",
    );
    assert!(
        right_recursive.parse::<Grammar>().unwrap().parse_input(input).next().is_some(),
        "right-recursive grammar failed to parse: {input}"
    );
}
```

### PR DESCRIPTION
**Pull request by CrockAgile**
Closes #117 
Closes #118 (hopefully! 🤞)
Closes #119
Closes #115 

## Try Again!

This PR is the result of iterating on #119. #119 attempted to resolve the same issue, but @amascolo generously raised examples that still failed.

This PR (maybe!) resolves these additional cases, which are now also included as tests.

I will include the identical "root cause" section here as #119 so that this PR may be readable on its own.

## Root Cause

Consider the grammar:

```text
<start> ::= <shortfail> | <longsuccess>
<shortfail> ::= <char> 'never'
<char> ::= 'a'
<longsuccess> ::= <long2>
<long2> ::= <long3>
<long3> ::= <long4>
<long4> ::= <char>
```

When parsing input "a", there are two routes: "shortfail" and "longsuccess". As the names suggest, "shortfail" requires fewer traversals, but always fails. "longsuccess" requires more traversal steps, and should eventually succeed.

The issue is caused because both paths predict the non-terminal "char". Practical Earley parsing requires de-duplicating predictions or else recursive grammars fall into infinite loops. The existing Earley implementation in BNF does roughly the following:

(work roughly alternates between the short and long routes because new traversals are appended to the end of the work queue)

```
* <start> ::= • <shortfail>
* <start> ::= • <longsuccess>
* <shortfail> ::= • <char> 'never'
* <longsuccess> ::= • <long2>
* <char> ::= • 'a'
* <long2> ::= • <long3>
* <char> ::= 'a' •
* <long3> ::= • <long4>
* <shortfail> ::= <char> • 'never' // <--- notice this does NOT succeed
* <long4> ::= • <char> // !!! this <char> prediction is IGNORED because an identical prediction was already made
```

All the `<longN>` productions are necessary because otherwise the `<longsuccess>` route is able to predict <char> before its completion.

> I am sorry if I have not explained this super clearly. It is a tricky problem! Funny aside, I actually thought of this bug while developing v0.4.0 . But I (wrongly) assumed there was something about the Earley algorithm which resolved it. I attempted to write a test, but I did not realize it would require so many intermediate non-terminals to expose. Woops!

## Existing Issues

Where this PR differs from #119 is its approach to "duplicate detection". Previously, duplicate Earley states/traversals were identified by which `Production` and how many `Term`s had been matched. This turns out to be insufficient, because partially "matched" `Production`s (i.e. `<shortfail> ::= <char> • 'never'`) could have matched non-terminals via different paths.

## New Duplicate Detection

Traversals now match/complete terms by building trees 🌳

A new prediction is the root trunk of a tree, and each matched/completed term adds a new branch. Assuming there are two different traversals which can complete `base`, a traversal tree segment may look like:

```mermaid
flowchart TD
0["dna ::= • base dna"] --> 1["dna ::= base=1 • dna"]
0["dna ::= • base dna"] --> 2["dna ::= base=2 • dna"]
```

### Performance

On my machine, there was seemingly _no performance cost_ to these changes. I believe there was a cost to adding the new logic for "prior completed" traversals. But that cost was offset by the improvement of traversal trees, instead of reference counted term matching vectors.

## Extra

Basically every time I have worked on an Earley bug, I have ended up adding the same manual logging to help with debugging. I decided to commit that logging this time!

There is a new `tracing::event!` which by default is a noop, but with the "tracing" feature enabled adds logging events.

For Earley, traversal state events are logged when created and during predict/scan/complete. It helps quite a bit with debugging!

### CODE REVIEW

**Comment by CrockAgile** [comment]
I again plan to leave this PR open to give some time for review. Also I still have to read it all over myself with fresh eyes, and add a lot of comments 😅

File: src/grammar.rs [hunk 1]
```diff
@@ -685,6 +690,158 @@ mod tests {
...
+        // 1. 'AND' <and> 'AND' <and> 'AND'
+        // 2. 'AND' <and> 'AND' 'AND' 'AND'
+        // 3. 'AND' 'AND' <and> 'AND' 'AND'
+        // 4. 'AND' 'AND' 'AND' <and> 'AND'
+        // 5. 'AND' 'AND' 'AND' 'AND' 'AND'
+        assert_eq!(
+            bnf.parse::<Grammar>().unwrap().parse_input(input).count(),
+            5
+        );
+    }
```
Comment (CrockAgile) [inline src/grammar.rs:843]: @amascolo are these parse trees what you expect?

```txt
<and> ::= <and> " AND " <terminal>
├── <and> ::= <and> " AND " <terminal>
│   ├── <and> ::= <terminal>
│   │   └── <terminal> ::= "AND"
│   │       └── "AND"
│   ├── " AND "
│   └── <terminal> ::= "AND"
│       └── "AND"
├── " AND "
└── <terminal> ::= "AND"
    └── "AND"

<and> ::= <and> " AND " <terminal>
├── <and> ::= <and> " " <terminal>
│   ├── <and> ::= <and> " " <terminal>
│   │   ├── <and> ::= <terminal>
│   │   │   └── <terminal> ::= "AND"
│   │   │       └── "AND"
│   │   ├── " "
│   │   └── <terminal> ::= "AND"
│   │       └── "AND"
│   ├── " "
│   └── <terminal> ::= "AND"
│       └── "AND"
├── " AND "
└── <terminal> ::= "AND"
    └── "AND"

<and> ::= <and> " " <terminal>
├── <and> ::= <and> " AND " <terminal>
│   ├── <and> ::= <and> " " <terminal>
│   │   ├── <and> ::= <terminal>
│   │   │   └── <terminal> ::= "AND"
│   │   │       └── "AND"
│   │   ├── " "
│   │   └── <terminal> ::= "AND"
│   │       └── "AND"
│   ├── " AND "
│   └── <terminal> ::= "AND"
│       └── "AND"
├── " "
└── <terminal> ::= "AND"
    └── "AND"

<and> ::= <and> " " <terminal>
├── <and> ::= <and> " " <terminal>
│   ├── <and> ::= <and> " AND " <terminal>
│   │   ├── <and> ::= <terminal>
│   │   │   └── <terminal> ::= "AND"
│   │   │       └── "AND"
│   │   ├── " AND "
│   │   └── <terminal> ::= "AND"
│   │       └── "AND"
│   ├── " "
│   └── <terminal> ::= "AND"
│       └── "AND"
├── " "
└── <terminal> ::= "AND"
    └── "AND"

<and> ::= <and> " " <terminal>
├── <and> ::= <and> " " <terminal>
│   ├── <and> ::= <and> " " <terminal>
│   │   ├── <and> ::= <and> " " <terminal>
│   │   │   ├── <and> ::= <terminal>
│   │   │   │   └── <terminal> ::= "AND"
│   │   │   │       └── "AND"
│   │   │   ├── " "
│   │   │   └── <terminal> ::= "AND"
│   │   │       └── "AND"
│   │   ├── " "
│   │   └── <terminal> ::= "AND"
│   │       └── "AND"
│   ├── " "
│   └── <terminal> ::= "AND"
│       └── "AND"
├── " "
└── <terminal> ::= "AND"
    └── "AND"
```

Comment (amascolo) [reply src/grammar.rs:843]: Yep, these look like the parse trees I was expecting!

Thanks even for writing them out in the same order as they appeared in https://github.com/shnewto/bnf/issues/117#issuecomment-1379165220

**Review by shnewto — APPROVED** [review]
looks great!

**Comment by CrockAgile** [comment]
snapshot testing has exposed some nondeterminism in the Earley parsing. the parse trees are valid, but for ambiguous grammars are parsed in inconsistent orders between test executions.

I will investigate this (likely a `Hashmap` or something 🙏). Otherwise, this PR is holding up to my local scrutiny. Once I resolve the nondeterminism issue, I plan to merge 🎊

File: tests/parse_input.rs [hunk 2]
```diff
@@ -0,0 +1,530 @@
...
+}
+
+#[test]
+fn empty() {
+    let grammar: Grammar = "<start> ::= \"\"".parse().unwrap();
+
+    let input = "";
+
+    let parses = grammar.parse_input(input);
+    assert_eq!(parses.count(), 1);
```
Comment (CrockAgile) [inline tests/parse_input.rs:121]: woops missed one

File: tests/parse_input.rs [hunk 3]
```diff
@@ -0,0 +1,530 @@
...
+    );
+    assert!(passes_3
+        .parse::<Grammar>()
+        .unwrap()
+        .parse_input(input)
+        .next()
+        .is_some());
+
+    assert!(
+        fails
```
Comment (CrockAgile) [inline tests/parse_input.rs:446]: should rename these cases now that they are passing
